import 'package:flutter/material.dart';

import '../models/event_preview.dart';
import '../models/match_preview.dart';
import '../../data/models/user_model.dart';

class SampleData {
  const SampleData._();

  static final List<EventPreview> events = <EventPreview>[
    EventPreview(
      title: 'Andex Meetup: Networking & Coffee',
      category: 'Комьюнити',
      time: 'Сегодня · 19:00',
      distance: '1,2 км от вас',
      badgeColor: const Color(0xFF5E60CE),
      attendees: 42,
      date: DateTime.now().add(const Duration(hours: 3)),
      location: 'Кофейня "The Brew", ул. Тверская 12',
      price: 0,
      attendeeNames: const <String>[
        'Алексей',
        'Мария',
        'Игорь',
        'Анна',
        'Дмитрий',
      ],
    ),
    EventPreview(
      title: 'Sunrise Yoga в Парке Горького',
      category: 'Здоровье',
      time: 'Завтра · 07:30',
      distance: '3,5 км от вас',
      badgeColor: const Color(0xFF4ECCA3),
      attendees: 18,
      date: DateTime.now().add(const Duration(days: 1, hours: 7, minutes: 30)),
      location: 'Парк Горького, Центральная поляна',
      price: 500,
      attendeeNames: const <String>['Ольга', 'Светлана', 'Екатерина'],
    ),
    EventPreview(
      title: 'Techno Night by Local DJs',
      category: 'Музыка',
      time: 'Пятница · 22:00',
      distance: '850 м от вас',
      badgeColor: const Color(0xFFFF8383),
      attendees: 76,
      date: DateTime.now().add(const Duration(days: 4, hours: 22)),
      location: 'Клуб "Forma", Трубная площадь 2',
      price: 1500,
      attendeeNames: const <String>['Максим', 'Виктория', 'Андрей', 'Полина'],
    ),
  ];

  static final List<MatchPreview> matches = <MatchPreview>[
    MatchPreview(
      id: 'user_1',
      name: 'Лиза',
      age: 24,
      gender: 'female',
      photoUrl: null,
      photos: const [],
      bio: 'Ищет напарника на TEDx',
      interests: const ['Технологии', 'Нетворкинг', 'Стартапы'],
      matchPercentage: 89,
      commonInterests: const <String>['Технологии', 'Нетворкинг', 'Стартапы'],
      latitude: null,
      longitude: null,
      userModel: UserModel(
        id: 'user_1',
        supabaseUid: 'sup_user_1',
        email: 'liza@example.com',
        displayName: 'Лиза',
        photoUrl: null,
        photos: const [],
        bio: 'Ищет напарника на TEDx',
        interests: const ['Технологии', 'Нетворкинг', 'Стартапы'],
        age: 24,
        gender: 'female',
        isOnboardingCompleted: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
    ),
    MatchPreview(
      id: 'user_2',
      name: 'Никита',
      age: 27,
      gender: 'male',
      photoUrl: null,
      photos: const [],
      bio: 'Пойдет на Jazz Rooftop',
      interests: const ['Джаз', 'Музыка', 'Вечеринки'],
      matchPercentage: 76,
      commonInterests: const <String>['Джаз', 'Музыка', 'Вечеринки'],
      latitude: null,
      longitude: null,
      userModel: UserModel(
        id: 'user_2',
        supabaseUid: 'sup_user_2',
        email: 'nikita@example.com',
        displayName: 'Никита',
        photoUrl: null,
        photos: const [],
        bio: 'Пойдет на Jazz Rooftop',
        interests: const ['Джаз', 'Музыка', 'Вечеринки'],
        age: 27,
        gender: 'male',
        isOnboardingCompleted: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
    ),
    MatchPreview(
      id: 'user_3',
      name: 'Камила',
      age: 22,
      gender: 'female',
      photoUrl: null,
      photos: const [],
      bio: 'Организует Art Picnic',
      interests: const ['Искусство', 'Пикники', 'Фотография', 'Дизайн'],
      matchPercentage: 92,
      commonInterests: const <String>['Искусство', 'Пикники', 'Фотография'],
      latitude: null,
      longitude: null,
      userModel: UserModel(
        id: 'user_3',
        supabaseUid: 'sup_user_3',
        email: 'kamila@example.com',
        displayName: 'Камила',
        photoUrl: null,
        photos: const [],
        bio: 'Организует Art Picnic',
        interests: const ['Искусство', 'Пикники', 'Фотография', 'Дизайн'],
        age: 22,
        gender: 'female',
        isOnboardingCompleted: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
    ),
  ];
}
