DO $$ BEGIN
  ALTER TYPE "ReportReason" ADD VALUE IF NOT EXISTS 'SPAM_PROFILE';
  ALTER TYPE "ReportReason" ADD VALUE IF NOT EXISTS 'FAKE_PROFILE';
  ALTER TYPE "ReportReason" ADD VALUE IF NOT EXISTS 'INAPPROPRIATE_PHOTOS';
  ALTER TYPE "ReportReason" ADD VALUE IF NOT EXISTS 'SCAM';
EXCEPTION
  WHEN undefined_object THEN null;
END $$;

