-- Demo events around Kirov for map/feed testing.
-- Safe to re-run: upsert by id.

BEGIN;

CREATE SCHEMA IF NOT EXISTS events;

INSERT INTO events."Event" (
  "id",
  "title",
  "description",
  "category",
  "location",
  "latitude",
  "longitude",
  "locationGeo",
  "dateTime",
  "endDateTime",
  "price",
  "imageUrl",
  "isOnline",
  "status",
  "maxParticipants",
  "createdById",
  "createdAt",
  "updatedAt"
)
VALUES
(
  'demo-event-kirov-jazz',
  'Джаз на набережной',
  'Живая музыка у Вятки, бесплатный вход.',
  'concert',
  'Киров, набережная Грина',
  58.6038,
  49.6675,
  ST_SetSRID(ST_MakePoint(49.6675, 58.6038), 4326)::geography,
  NOW() + INTERVAL '2 days',
  NOW() + INTERVAL '2 days 3 hours',
  0,
  'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800',
  false,
  'APPROVED',
  120,
  'fake-match-anna',
  NOW(),
  NOW()
),
(
  'demo-event-kirov-run',
  'Утренний забег 5 км',
  'Старт у театра на Спасской, темп свободный.',
  'sport',
  'Киров, пл. Островского',
  58.5965,
  49.6602,
  ST_SetSRID(ST_MakePoint(49.6602, 58.5965), 4326)::geography,
  NOW() + INTERVAL '1 day',
  NOW() + INTERVAL '1 day 2 hours',
  0,
  'https://images.unsplash.com/photo-1476480862126-209bfaa8dba8?w=800',
  false,
  'APPROVED',
  80,
  'fake-match-igor',
  NOW(),
  NOW()
),
(
  'demo-event-kirov-art',
  'Выставка молодых художников',
  'Работы студентов ВятГГУ, вход свободный.',
  'exhibition',
  'Киров, ул. Карла Маркса, 72',
  58.6102,
  49.6821,
  ST_SetSRID(ST_MakePoint(49.6821, 58.6102), 4326)::geography,
  NOW() + INTERVAL '3 days',
  NOW() + INTERVAL '3 days 6 hours',
  0,
  'https://images.unsplash.com/photo-1460661419201-fd4cecdfde94?w=800',
  false,
  'APPROVED',
  200,
  'fake-match-anna',
  NOW(),
  NOW()
),
(
  'demo-event-kirov-tech',
  'IT-митап: мобильная разработка',
  'Доклады про Flutter и микросервисы, нетворкинг после.',
  'conference',
  'Киров, бизнес-центр «Гостиный двор»',
  58.5991,
  49.6528,
  ST_SetSRID(ST_MakePoint(49.6528, 58.5991), 4326)::geography,
  NOW() + INTERVAL '5 days',
  NOW() + INTERVAL '5 days 4 hours',
  0,
  'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
  false,
  'APPROVED',
  60,
  'fake-match-igor',
  NOW(),
  NOW()
),
(
  'demo-event-kirov-party',
  'Вечеринка у друзей',
  'House-party с DJ-сетом, 18+.',
  'party',
  'Киров, мкр. Ломовой',
  58.6184,
  49.6419,
  ST_SetSRID(ST_MakePoint(49.6419, 58.6184), 4326)::geography,
  NOW() + INTERVAL '4 days',
  NOW() + INTERVAL '4 days 5 hours',
  500,
  'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800',
  false,
  'APPROVED',
  40,
  'fake-match-anna',
  NOW(),
  NOW()
)
ON CONFLICT ("id") DO UPDATE SET
  "title" = EXCLUDED."title",
  "description" = EXCLUDED."description",
  "category" = EXCLUDED."category",
  "location" = EXCLUDED."location",
  "latitude" = EXCLUDED."latitude",
  "longitude" = EXCLUDED."longitude",
  "locationGeo" = EXCLUDED."locationGeo",
  "dateTime" = EXCLUDED."dateTime",
  "endDateTime" = EXCLUDED."endDateTime",
  "price" = EXCLUDED."price",
  "imageUrl" = EXCLUDED."imageUrl",
  "status" = EXCLUDED."status",
  "updatedAt" = NOW();

COMMIT;
